// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeOlJAKbqzqbcCloMmXso_ScVlPVapXfI',
    appId: '1:834316824347:web:254a98594df0070615adbe',
    messagingSenderId: '834316824347',
    projectId: 'scholar-chat2',
    authDomain: 'scholar-chat2.firebaseapp.com',
    storageBucket: 'scholar-chat2.appspot.com',
    measurementId: 'G-Q4P11P91WE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCilupwcTp9yShjJ3xoVSrU43xSw9jV6dI',
    appId: '1:834316824347:android:f2fcb4130e1fedee15adbe',
    messagingSenderId: '834316824347',
    projectId: 'scholar-chat2',
    storageBucket: 'scholar-chat2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo_Ud0Ea7NtBZUKyvLO_9Ta1BmevBwooQ',
    appId: '1:834316824347:ios:d65f40b524c421e915adbe',
    messagingSenderId: '834316824347',
    projectId: 'scholar-chat2',
    storageBucket: 'scholar-chat2.appspot.com',
    iosClientId: '834316824347-97j62u1frcoe3ea2gcaf0i45j8c9oih5.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo_Ud0Ea7NtBZUKyvLO_9Ta1BmevBwooQ',
    appId: '1:834316824347:ios:d65f40b524c421e915adbe',
    messagingSenderId: '834316824347',
    projectId: 'scholar-chat2',
    storageBucket: 'scholar-chat2.appspot.com',
    iosClientId: '834316824347-97j62u1frcoe3ea2gcaf0i45j8c9oih5.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat2',
  );
}
